name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Flutter SDK
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3' # Updated to match the required Dart SDK version
          channel: 'stable' # Specify the channel if necessary

      - name: Install dependencies
        run: flutter pub get

      # Check formatting (uncomment if needed)
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .

      # Analyze project source with Flutter
      - name: Analyze project source
        run: flutter analyze

      # Run tests for the Flutter project
      - name: Run tests
        run: flutter test
